### ISSUE TITLE
Possible switch to JSON for imgur

### ISSUE THREAD

**Issue by kimonakos** [oliverayris/image-grabber#5]
Beautiful Soup at the moment takes in the text of the website response, rather than the JSON. This means that the page is eventually interpreted as a long string. This means that if any image id in a page such as [this](https://imgur.com/ajaxalbums/getimages/n7mTb/hit.json?all=true) has a substring "hash" or "ext", the process will assume there is another image.

Anyone have experience on how to turn that particular body of such a page into a real dictionary such that it can be searched normally?

**Comment by caffeinatedMike** [comment]
I'll work on this today once my python 3.5 install completes.

**Comment by kimonakos** [comment]
Great, thanks! Let me know if some of my code needs explanation. It's my first script so it's pretty rough.

**Comment by caffeinatedMike** [comment]
Seems really straightforward, good structure. I'll have the pull request ready in a few.

**Comment by kimonakos** [comment]
Hey thanks a lot! That looks a lot better! Very concise.

**Comment by caffeinatedMike** [comment]
Glad to help! Let me know if you need anymore help :) I like helping on random projects.

**Comment by kimonakos** [comment]
I am having problems with scrapping google images. I will be raising a separate issue for that.

**Comment by kimonakos** [comment]
New issue is up [here](https://github.com/oliverayris/image-grabber/issues/7)
