### ISSUE TITLE
Beatifulsoup not finding rg_meta values in classes.

### ISSUE THREAD

**Issue by kimonakos** [oliverayris/image-grabber#7]
I'm suspecting that the page loads dynamically, therefore a solution to this problem would be to parse a JSON version of the page. Not sure exactly how to troubleshoot this.

To test the case one can use [this](https://www.google.com/search?q=banana&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiPtsu-tLzXAhXoJJoKHbqLBswQ_AUICigB&biw=1680&bih=902) as command line argument.

**Comment by caffeinatedMike** [comment]
Due to the way Google performs it's searches you will not be able to scrape the html of the url you mention. My suggestion is that we use the [Google Custom Search API](https://developers.google.com/custom-search/json-api/v1/reference/cse/list) and insert the necessary parameters that we can dissect from the provided url. Looking at the provided url I don't see any parameters that would be needed to perform the API call other than the query. Thoughts?

**Comment by kimonakos** [comment]
That's a shame. It looks like [this suggestion](https://stackoverflow.com/a/35810041). I didn't want to depend on APIs at all, but I guess we could do it. I think we should try to make sure that we capture all important info from the url besides the query, since one might decide to narrow the search to certain image sizes for example. I will have to study how Google changes the url for such cases.

On the other hand, here are a couple of cases where I don't see them depending on the Custom Search API: [1](https://github.com/hardikvasa/google-images-download/blob/master/google-images-download.py) [2](https://gist.github.com/genekogan/ebd77196e4bf0705db51f86431099e57).

I'm in GMT+2 time zone so I will have to return to this tomorrow.

**Comment by caffeinatedMike** [comment]
Oh wait, nevermind! Just had to change your User-Agent to a legitimate one to imitate a browser. Working on the fix now. Will likely not be able to finish it until tomorrow as I have things to do.

**Comment by caffeinatedMike** [comment]
Not done yet, still need to add error-handling, but it's just about done. You can see the edits [here](https://github.com/caffeinatedMike/image-grabber/commit/d8043fd018bed3d590025886b5bbff74096b0f98)

**Comment by kimonakos** [comment]
Ha I hadn't thought of trying that. Good catch. Do user agents need to be updated from time to time to reflect newer browser versions? Or is that not actually necessary?

**Comment by caffeinatedMike** [comment]
Nope, as long as you have a valid user agent you shouldn't need to change it. So, the changes you see in my fork right now download the images from the search. However, partway through it error due to an image name I believe. Will look at it tomorrow morning and do another pull request for you when it's done.

**Comment by kimonakos** [comment]
Awesome! That's great to hear. No worries, take your time.

**Comment by caffeinatedMike** [comment]
The new pull request fixed the google image grabbing. However, you'll probably want to do a little cleaning up of the filenames now. Some are using the entire url url-encoded. Here are the results.

```
C:\Users\mhill\Downloads\image-grabber-master (1)\image-grabber-master>script.py
 "https://www.google.com/search?q=banana&source=lnms&tbm=isch&sa=X&ved=0ahUKEwiP
tsu-tLzXAhXoJJoKHbqLBswQ_AUICigB&biw=1680&bih=902"

Downloading page: https://www.google.com/search?q=banana&source=lnms&tbm=isch&sa
=X&ved=0ahUKEwiPtsu-tLzXAhXoJJoKHbqLBswQ_AUICigB&biw=1680&bih=902

Downloading image Banana3-1020x765.jpg
Saved!
Downloading image 271157-bananas.jpg
Saved!
Site not yet supported: https://img.purch.com/h/1000/aHR0cDovL3d3dy5saXZlc2NpZW5
jZS5jb20vaW1hZ2VzL2kvMDAwLzA2NS8xNDkvb3JpZ2luYWwvYmFuYW5hcy5qcGc=
Downloading image bananas.jpg
Saved!
Downloading image Banana.jpg
Saved!
Downloading image 1200px-Banana-Single.jpg
Saved!
Downloading image banana-nutrition-facts.jpg
Saved!
Downloading image 71OebfTPCiL._SX466_.jpg
Saved!
Downloading image 180148.jpg
Saved!
Downloading image banana-crop.jpg
Saved!
Downloading image o-142765670-facebook.jpg
Saved!
Downloading image AN74-Banana_smoothie-1296x728-Header.jpg
Saved!
Downloading image Banana-3-bananas-34512789-1000-1000.jpg
Saved!
Downloading image banana-42793_960_720.png
Saved!
Downloading image RipenessBlend.png
Saved!
Downloading image banana-day1-e1429079484250.jpg
Saved!
Downloading image 501px-Banana_and_cross_section.jpg
Saved!
Downloading image good-reasons-to-eat-a-banana-today.jpg
Saved!
Downloading image 41922F6200000578-4620876-image-a-14_1497950660908.jpg
Saved!
Downloading image DN1rD8SW0AEokry.jpg
Saved!
Downloading image sterile-banana.jpg
Saved!
Downloading image banana.jpg
Saved!
Downloading image benefits-of-eating-banan.jpg
Saved!
Downloading image AN132-Bananas-on-yellow-1296x728-Header.jpg
Saved!
Downloading image Banana-2.jpg
Saved!
Downloading image qzj0vbr6lzrasvupvflt.jpg
Saved!
Downloading image banana_620x350_61478592730.jpg
Saved!
Downloading image http%3A%2F%2Fo.aolcdn.com%2Fhss%2Fstorage%2Fmidas%2Fffa43721fa
5500761c5adf564ca345ff%2F204947894%2F171262723.jpg
Saved!
Downloading image banana-bread-ingredients-1.jpg
Saved!
Downloading image banana.jpg
Saved!
Downloading image BANANA-GINGER-SMOOTHIE.jpg
Saved!
Downloading image 170px-Banana_farm_Chinawal.jpg
Saved!
Downloading image 577070349_960.jpg
Saved!
Site not yet supported: https://target.scene7.com/is/image/Target/15993444_Alt01
?wid=520&hei=520&fmt=pjpeg
Downloading image banana-flasher-costume.jpg
Saved!
Downloading image Health-Benefits-of-Bananas.jpg
Saved!
Downloading image banana-bananas.png
Saved!
Downloading image cdb94420-1192-4a5c-920a-b7328ec99a9f._SR970,300_.jpg
Saved!
Downloading image 0004394411_10.jpg
Saved!
Downloading image brass_banana.jpg
Saved!
Downloading image Banana_(1).jpg
Saved!
Site not yet supported: https://s0.wp.com/wp-content/mu-plugins/wpcom-smileys/tw
emoji/2/svg/1f34c.svg
Downloading image 220px-Bananas.jpg
Saved!
Downloading image photo.jpg
Saved!
Downloading image Banana-Yellow-Single.jpg
Saved!
Downloading image banana.jpg
Saved!
Downloading image Lady-Finger-Bananas-578fd21a3df78c09e97403fa.jpg
Saved!
Downloading image DSC_6505.jpg
Saved!
Downloading image banana.jpg
Saved!
Downloading image peeled-banana.jpg
Saved!
Downloading image how-to-store-banana-ripe-hero-getty.jpg
Saved!
Site not yet supported: https://atmedia.imgix.net/bfe76cac181b24d244e698fa522f4c
273228a182?w=800&fit=max
Downloading image banana_budvase_w.jpg
Saved!
Downloading image 2-1-740x360.jpg
Saved!
Downloading image bananas-556841737.jpg
Saved!
Downloading image coconut-banana-ice-cream-2.jpg
Saved!
Downloading image banana.jpg
Saved!
Downloading image banana.jpg
Saved!
Downloading image 1394587617072.jpeg
Saved!
Downloading image banana-tree-320x480.jpg
Saved!
Downloading image bananainfographic01.jpg
Saved!
Downloading image maxresdefault.jpg
Saved!
Downloading image VEGAN-BANANA-BREAD-CINNAMON-ROLLS.jpg
Saved!
Downloading image Bananavarieties.jpg
Saved!
Downloading image banana-for-baby.jpg
Saved!
Downloading image banana_500x300_81455523540.jpg
Saved!
Downloading image peeled-banana.jpg
Saved!
Downloading image bananas-pattern-design_1270-100.jpg
Saved!
Downloading image 271157-bananas-oatmeal.jpg
Saved!
Downloading image banana-protein-shake-500x366.jpg
Saved!
Downloading image banana-714.jpg
Saved!
Downloading image sub-buzz-17594-1498418864-1.jpg
Saved!
Site not yet supported: https://atmedia.imgix.net/10771a2d718a3ed3b82f3d4b91e474
d700156b2f?w=800&fit=max
Downloading image Ripen-Bananas-Fast-9.jpg
Saved!
Downloading image a36629516688b655388f3fbb4bf66d81--banana-art-pink-banana.jpg
Saved!
Downloading image o-BANANAS-facebook.jpg
Saved!
Site not yet supported: https://media.istockphoto.com/photos/banana-picture-id12
0492078?k=6&m=120492078&s=612x612&w=0&h=a4FNBRMoufM4ewkS2RiChWoO3be5HTmRl6_6dP9Q
B9I=
Downloading image banana-pudding-cheesecake-sl-x.jpg
Saved!
Downloading image banana_picture_2_jpg.jpg
Saved!
Downloading image 1249337589_f0fabec151_o-1920x1273.jpg
Saved!
Site not yet supported: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d
c/Kaeng_yuak.JPG/180px-Kaeng_yuak.JPG
Downloading image banana-in-fist-support-1.jpg
Saved!
Downloading image 2000px-Bananas.svg.png
Saved!
Downloading image banana-peeled.jpg
Saved!
Downloading image banana-dogs.jpg
Saved!
Downloading image banana-bread-horiz-a-1600.jpg
Saved!
Downloading image pxqrocxwsjcc_2jA159j1xiqs6IGCi8Oe0A_banana-bread-3-ways_square
Thumbnail_en.png
Saved!
Downloading image banana-phloem-bundles-today-tease-170620_8a0d76f79592a70d16b3f
78b28e6e43c.jpg
Saved!
Downloading image banana_large_single.png
Saved!
Downloading image banana-trees-289022372.jpg
Saved!
Downloading image landscape-1489774221-delish-banana-pancake-dippers-2.jpg
Saved!
Site not yet supported: http://www.iconarchive.com/download/i19918/indeepop/rave
/yammi-banana.ico
Downloading image 1033249144001_1937277925001_ari-origin05-arc-170-1351721501066
.jpg
Saved!
Downloading image apple-banana-milkshake-getty-2003-x-1500-56a645bf5f9b58b7d0e0c
364.jpg
Saved!
Downloading image Ripe-Banana.jpg
Saved!
Downloading image why-you-should-never-throw-away-your-banana-peel.jpg
Saved!
Downloading image 1406932836501.jpeg
Saved!
Downloading image 41dcFmV1IGL._SL500_AC_SS350_.jpg
Saved!
Downloading image peachmangobananabreadtext1.jpg
Saved!
Downloading image banana-151553_960_720.png
Saved!

92 images downloaded.
```

**Comment by kimonakos** [comment]
Holy smokes that was amazing.

With regards to the naming scheme, to be fair, it is working as expected. I might give it some thought in the next few days. I might just rename all images into numbers when I decide to add the ability to setup a custom picture directory location.

By the way, I'm not quite sure where to start with JSON. Any tips?

**Comment by caffeinatedMike** [comment]
Glad you like the changes :)

As for JSON, there isn't really much to it. The JSON module turns a JSON object into a navigable object of nested lists and dictionaries. If you've navigated JSON in any other language it should be easy to learn the module. If not, the python documentation for it is very helpful and can be found [here](https://docs.python.org/3/library/json.html). 

Let me know what's next and I'll see what I can do!

**Comment by kimonakos** [comment]
Python is the only language I have scripting experience with, so that resource was pretty useful. It actually looks simpler than I was expecting.

To be fair, I wasn't planning to make my project too advanced. In fact, there is [ripme](https://github.com/4pr0n/ripme) which a pretty thorough piece of kit that does the exact same thing as this.

My goal has been to familiarise myself more with Python and Git/Github so I can dive into other open source projects here. I'm probably going to be looking to do what you are doing now with my project; helping other people out, even if it's just documentation.

My next goal is giving the option for a custom location for the picture directory and then, if I'm not too bored with it, I'll add support for flickr. I'll definitely give you a shout if I find myself stuck again.
