### ISSUE TITLE
add website support

### ISSUE THREAD

**Issue by gruiick** [oliverayris/image-grabber#9]
hi,
thank you for your usefull script.

Could you please add https://zizki.com/ (+18 adult content)? It as a validator popup.

Bests

**Comment by kimonakos** [comment]
Hi there,

Thank you for using my script. I apologise for just seeing this ticket. 

I’m certainly interested in adding support, unfortunately I won’t be able to do so for a few months due to work responsibilities. 

However, I will let you know when I start working on this.
